### ISSUE TITLE
could u tell me how to download file from client to server

### ISSUE THREAD

**Issue by CrystalSober** [iagox86/dnscat2#100]
i succeed making the dos tunnel.
but could u please tell me how to use the download order.
when i use download <from>[to] .
it return "error opening file for reading"
thank u very much

**Comment by iagox86** [comment]
You want to use "download [filename]", as you're doing.

Because of the shell parsing, slashes are weird. A few things to try:

Single quotes: download '/path/to/file'

Double up backslashes: download c:\\path\\to\\file

Double up backslashes and quotes: download "c:\\path\\to\\file"

One of those should work! You might also want to add a destination:

download '/path/to/file' '/tmp/file'

**Comment by CrystalSober** [comment]
thank you very much.
i tried as you said  and got succeed.
in the version i download the order should be:
download 'C:\\Users\\cccsober\\Desktop\\dir\\txt_in_file.txt'

thank you very much.
