### ISSUE TITLE
Windows client terminates with "NOT IMPLEMENTED"

### ISSUE THREAD

**Issue by mattchess50** [iagox86/dnscat2#90]
Output attached.
[dnscat2_output.txt](https://github.com/iagox86/dnscat2/files/147388/dnscat2_output.txt)

**Comment by iagox86** [comment]
Hey,

It looks like you're using "example.com" as the domain. Since you don't own that domain, it's not gonna work.

There are two options:
a) You can use a domain that you own, using an authoritative DNS server like [in this doc](https://github.com/iagox86/dnscat2/blob/master/doc/authoritative_dns_setup.md)
b) You can use a direct IP connection, by using ./dnscat --dns server=x.x.x.x,port=53

The reason you're seeing weird output is because example.com is returning A records, which we're trying to parse as dnscat2 records, which they aren't.

Hope that helps!

You also mentioned you got a segfault.. if you're able to repro the segfault, can you follow the instructions I just wrote [here](https://github.com/iagox86/dnscat2/blob/master/doc/how_to_bug_report.md), particularly around the segfault section at the bottom, and re-open this (or open a new one) with that info?

Thanks!
